### ISSUE TITLE
Replace argparse by begins

### ISSUE THREAD

**Issue by dridk** [natir/bench_rev_comp#4]
"Begins" is a new python package dedicated to parse arg. It uses decorator and it is easier than argparse. 

http://sametmax.com/sept-petites-libs-qui-changent-la-vie-dun-dev-python/
http://begins.readthedocs.org/en/latest/

**Comment by natir** [comment]
You can make a pull request, if you want but i'm not sure this new module reduce and simplify the code.

But if the code is better i can accept your pull request

**Comment by natir** [comment]
After test begins is a interesting package but parse of python function argument isn't perfect, and the type of argument (positional or keyword isn't good).

I close this issue.
